name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build with Next.js
        run: pnpm run build
        env:
          NODE_ENV: production

      - name: Add .nojekyll file
        run: touch out/.nojekyll
      
      - name: Fix language directory structure
        run: |
          # Copy index.html to root
          if [ -f public/index.html ]; then
            cp public/index.html out/index.html
          fi
          # Copy language HTML files to their directories
          for lang in en fr ja; do
            if [ -f "out/${lang}.html" ]; then
              mkdir -p "out/${lang}"
              cp "out/${lang}.html" "out/${lang}/index.html"
            fi
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
